Adjust Chrony_Conf Control
mitre/redhat-enterprise-linux-8-stig-baseline pull request #31
Opened 2024-10-24 20:34 UTC by DMedina6

Adjusts control to account for multiple values / arrays in both the inspec.yml input and the chrony.conf configuration file.

Edge case: 
This control passes when the chrony.conf file has fewer servers than the inspec.yml input but all values are valid.

      chrony_conf.server = [10.90.21.160]
      input('authoritative_timeserver') = [10.90.21.160, 10.90.21.178]

^ this would result in a pass.

This may be desirable if user wants to have several possible correct values but the configuration file only needs to have a subset of those values.

2024-10-24 20:58 UTC, wdower commented
> This may be desirable if user wants to have several possible correct values but the configuration file only needs to have a subset of those values.

So this is how I read this requirement. The STIG wants you to have _a_ valid timeserver, not an exact list. So your edge case is actually desired behavior.

2024-10-24 23:34 UTC, aaronlippold commented
The input in the input.yml is a list of 'valid timeservers' so having at least one of them and having maxpool be <= 16 are the two conditions that should be true.

The check text says 'a valid server' not 'all listed serververs must be in the config file'

We could, if you wanted, add an input for 'exact timeservers' to udpate the logic of the check to ensure that all listed timeservers in the input are configured and have a maxpool of <= 16. 

Also why are we so worried about the array vs string. The resource seems to return an array of strings, Just flatten it and fail fast if the flattened array is empty? nil?

2024-10-24 23:36 UTC, aaronlippold commented
https://github.com/inspec/inspec/blob/main/lib/inspec/resources/chrony_conf.rb#L56

2024-10-25 14:51 UTC, wdower approved these changes
This seems like cleanup to the code which doesn't meaningfully change its function. LGTM.

2024-10-25 14:53 UTC, wdower requested changes
Wait, read it again and realized that this is forcing _all_ timeservers to be valid. We want _minimum of one_ to be valid.

Suggest using `.any?` on the list of timeservers and checking for inclusion in the authorized servers list.

2024-10-25 16:56 UTC, DMedina6 commented
> https://github.com/inspec/inspec/blob/main/lib/inspec/resources/chrony_conf.rb#L56

This uses SimpleConfig utility to parse the chrony.conf file. Isn't this line saying that in the case that there is one value in the array it'll just return the string itself instead?

https://github.com/inspec/inspec/blob/ec9724ed1b7ee4f04fa66fa6eee0b5e89a708b02/lib/inspec/utils/simpleconfig.rb#L42

return match[start_idx] if values == 1

2024-10-25 16:59 UTC, DMedina6 commented
> Wait, read it again and realized that this is forcing _all_ timeservers to be valid. We want _minimum of one_ to be valid.
> 
> Suggest using `.any?` on the list of timeservers and checking for inclusion in the authorized servers list.

Yeah, and to be fair it doesn't seem to make sure that the specific timeserver being checked for has a valid maxpool value (or do all servers regardless of validity need a maxpool <= 16?)

2024-10-29 15:08 UTC, wdower commented
> Yeah, and to be fair it doesn't seem to make sure that the specific timeserver being checked for has a valid maxpool value (or do all servers regardless of validity need a maxpool <= 16?)

Good point. From the fix text, it looks like maxpoll needs to be set per-server.

2024-10-29 17:54 UTC, DMedina6 commented
Modified the control to check corresponding maxpoll values instead of all of them separately. 

@aaronlippold mentioned an authoritative_timeserver_exact input as well that would instead check if every value in it exists in the chrony.conf file? Would this allow for additional entries or are the entries in this new input the only ones that would be allowed?

2024-12-31 16:25 UTC, aaronlippold commented
@wdower  @Amndeep7 This would require an update to the inspec.yml version and and updated release of the profile correct?

2024-12-31 16:27 UTC, Amndeep7 commented
> @wdower  @Amndeep7 This would require an update to the inspec.yml version and and updated release of the profile correct?

Yes and also probably an equivalent PR on the rhel9 repo

2025-01-13 19:48 UTC, DMedina6 commented
Updates made. Implemented an 'exact' case where all inputted timeservers must be validated. 

I did change the inspec.yml input from "authoritative_timeserver" (string) to "authoritative_timeservers" (array). Not sure if this will disrupt existing workflows for other projects.

2025-01-13 22:14 UTC, aaronlippold commented
don't forget to update the release version number in the `inspec.yml` as part of your PR

2025-01-14 16:15 UTC, em-c-rod commented
> don't forget to update the release version number in the `inspec.yml` as part of your PR
 
Per team discussion, this can be left alone here and updated when a release is done.
"The version attribute in inspec.yml is managed during releases so you shouldn't change it in every merged branch, just when you cut a new release."
https://mitre.github.io/saf-training/courses/profile-dev-test/12.html#_3-implementation

2025-01-14 16:44 UTC, DMedina6 commented
> > don't forget to update the release version number in the `inspec.yml` as part of your PR
> 
> Per team discussion, this can be left alone here and updated when a release is done. "The version attribute in inspec.yml is managed during releases so you shouldn't change it in every merged branch, just when you cut a new release." https://mitre.github.io/saf-training/courses/profile-dev-test/12.html#_3-implementation

This is what I thought as well

2025-01-14 17:14 UTC, em-c-rod requested changes
Left some comments, and it also looks like the tests need some exploration to make sure they are passing prior to merge.

2025-01-14 17:14 UTC, em-c-rod commented on controls/SV-230484.rb
> +    # Check for valid maxpoll value <17
I would change the <17 to <= 16 to match the control language.

2025-01-14 17:14 UTC, em-c-rod commented on inspec.yml
> +  - name: authoritative_timeservers_exact
```suggestion
  - name: exact_authoritative_timeservers_match_enabled
```

Or `match_all_authoritative_timeservers_exact`
Or `all_authoritative_timeservers_must_match`

These may not be good names, but I would consider changing the name to make it more clear that this is a boolean value. Based on the code, I expected it to be a list of exact authoritative timeservers.

2025-02-06 17:57 UTC, jrmetzger commented
Regex works:

Example:

Inputs: 
authoritative_timeserver: 'test(first|second)test(1|2).domain.test iburst maxpoll 16'

Values:
test**first**test**1**.domain.test iburst maxpoll 16
test**second**test**1**.domain.test iburst maxpoll 16
test**first**test**2**.domain.test iburst maxpoll 16
test**second**test**2**.domain.test iburst maxpoll 16

2025-03-20 15:59 UTC, merged